### ISSUE TITLE
Save my co-hosted site list

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/ipfs-cohost#1]
I'd really like this to store the list of sites I want to co-host for a few reasons:

1. I want to be able to update the pinned versions easily `ipfs-cohost update` (or maybe a daemon that does this automatically?)
2. I do not remember what I'm co-hosting, I'd like to be able to list them out and then I can inspect the current size that they're taking up
3. When updating a co-hosted website I'd like it to unpin the old version to recover some disk space

Maybe this could all be achieved without state if pins had tags in IPFS...

**Comment by lidel** [comment]
We are discussing MFS-based scheme for storing and tracking cohosted websites that aims to address those concerns. It removes the need for custom config files and pinning, focusing on convention over configuration.

Initial draft at: https://github.com/ipfs-shipyard/cohosting/pull/2, feedback would be appreciated
