### ISSUE TITLE
Change to `full` by default

### ISSUE THREAD

**Issue by hacdias** [ipfs-shipyard/ipfs-cohost#11]
As per the conversation on https://github.com/ipfs-shipyard/ipfs-cohost/pull/5#discussion_r341254469, the next move is to change from `lazy` to `full` cohosting by default.

> @lidel https://github.com/ipfs-shipyard/ipfs-cohost/pull/5#discussion_r341254469
> >  I think for a command line utility where I'm explicitly adding sites I want to cohost the default should be full [..]
> 
> I agree the CLI expectation is "full", but English Wikipedia is 650GB and we have no API to track progress of `refs -r` once `add --full` is executed :(
People may not understand why `add` takes _days_ to complete.
> 
> Some ideas:
> 
> - **(A)** default CLI to "full", but inform user about the size of added website, giving an option to cancel before fetch starts
> - **(B)** default CLI to "full", but fail if added website is more than X Megabytes and ask user to pass explicit `--full` to indicate they are ok with the cost
> - **(C)** return an error on `add` without explicit `--lazy` or `--full` (require explicit decision)
>
> I think I like **(B)** the most, but perhaps there is a simpler way to address this?

@alanshaw, @lidel and I agree that B might be the best. Now the question is, more than how much megabytes? Personally, I don't know how to evaluate how much is too much, but I believe 100 MB would be _not_ be too much, but we also have to take into consideration the time it would take.

Wdyt?

**Comment by alanshaw** [comment]
Wow, I hope most websites aren't 100MB. I would pitch this much lower like 10MB! Even that feels big to me.

**Comment by hacdias** [comment]
Here's the proof:

```console
$ ipfs object stat $(ipfs dns ipfs.io) --human
NumLinks:       13
BlockSize:      652
LinksSize:      650
DataSize:       2
CumulativeSize: 10 MB
```

Don't ask me how though :O

**Comment by hacdias** [comment]
I believe all of those docs where the _old_ docs and could be safely removed...

**Comment by olizilla** [comment]
Full by default please. Could prompt the user if the website is > 1GB, or larger than disk... with a `Ok (Y/n)` prompt... along with a `--force` flag so scripts can still use it without user intervention.
